### ISSUE TITLE
Windows Update and WaaSMedicSvc cannot be enabled

### ISSUE THREAD

**Issue by zsnjuts** [WereDev/Wu10Man#14]
When I want to re-enable Windows Update, I find it not in the list of windows services (services.msc) and not in the list of Wu10Man either.
![image](https://user-images.githubusercontent.com/16850617/62049038-f9328700-b240-11e9-965c-45188d21e9e5.png)
Although WaaSMedicSvc is in the list, it cannot be enabled. After I enable it in Wu10Man and reboot, it still not works. If I start it manually, Windows will say the system cannot find the file specified.
So now both services have broken. Help needed. Thanks.

**Comment by WereDev** [comment]
Can you send me your logs?

In the mean time, if you look in your `C:\Windows\System32` folder, you should see two files starting with `Wu10Man_`.  Remove that prefix and then restart Wu10Man.  That should allow the services to be reconfigured.

**Comment by zsnjuts** [comment]
Unfortunately I use Wu10Man directly without unzipping so the log recording the process of disabling Windows Update cannot be found. But I have the lastest log below and I hope it can be helpful.
[2019-07-30.log](https://github.com/WereDev/Wu10Man/files/3444851/2019-07-30.log)
It seems that besides the two `Wu10Man_` prefixed files (`Wu10Man_wuaueng.dll` and `Wu10Man_WaaSMedicSvc.dll`), there already exist `wuaueng.dll` and `WaaSMedicSvc.dll`. Do I need to delete the two `Wu10Man_` files directly?
BTW, I have trouble when I rename/delete the `Wu10Man_` prefixed files because the system says that I need the priviledge provided by TrustedInstaller.

**Comment by WereDev** [comment]
Can you try to disable and reenable the services and send me the logs from that run?

If the non-Wu10Man files already exists, that means something already put them back.  Not sure what that process might have been.  But in that case, it is likely the services are running.  You should be able to check this in the Services manager.  Though I would expect Wu10Man to also show them as running.

**Comment by zsnjuts** [comment]
I have disable and reenable it, and the log is here. The log looks really normal.
[2019-07-30.log](https://github.com/WereDev/Wu10Man/files/3444876/2019-07-30.log)
I still cannot find `Windows Update` in the services manager and cannot start `WaaSMedicSvc` either.
Is it possible that the non-Wu10Man files exist because I tried to fix Windows Update by the command `sfc /scannow` before ?

**Comment by WereDev** [comment]
Hhmm...nothing in the logs would indicate any sort of error.  It's possible that sfc could have put things in an odd state, though I can't imagine anything removing the Windows Update service.

When you open the Services control, do you see the Windows Update and Windows Update Medic Service?

![image](https://user-images.githubusercontent.com/16233329/62136172-2adf3880-b2a9-11e9-85ea-6b95b261b653.png)

**Comment by zsnjuts** [comment]
They are not shown in the list and that's what we are talking about 😂

**Comment by WereDev** [comment]
What is at this registry key on your system?
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\wuauserv
```

**Comment by zsnjuts** [comment]
`wuauserv` doesn't exist under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services` in the registry.
![image](https://user-images.githubusercontent.com/16850617/62184966-0b243f00-b393-11e9-863c-df1f68002250.png)

**Comment by WereDev** [comment]
That's kind of what I figured was going on and what I was fearing.

For the immediate fix, I'm including a zip of a wuauserv reg file.  You will need to backup your registry file, merge this file in, and then reboot.  That should restore Windows Update.
[wuauserv.zip](https://github.com/WereDev/Wu10Man/files/3452678/wuauserv.zip)

As food for thought, Wu10Man does not delete that key from the registry.  I find it unlikely that sfc did it either.  Something like CCleaner or other registry repair software might have done it though.  Many of them look for registry keys that reference files that don't exist.  Since Wu10Man does rename the main file, it might have identified this as a deprecated key and removed it.  It's also possible, though unlikely, that an anti-virus/malware tool did it, but they usually don't check if keys are valid, just if they fall into the realm of malware.  There's also the slight chance that you do have some form of virus or malware on your system.  Some of them do go to rather drastic lengths to stop you from getting Windows Defender updates which does come through the Windows Update service.

**Comment by zsnjuts** [comment]
I have merged it and rebooted, but it doesn't seem to work. Windows Update still is not in the list of Wu10Man and service manager.
![image](https://user-images.githubusercontent.com/16850617/62264368-2f932080-b452-11e9-977e-278001017f9f.png)

**Comment by zsnjuts** [comment]
However, I disabled and reenabled WaaSMedicSvc in Wu10Man and rebooted, now Windows Update is back! It also appears in the list of service manager. Thanks very much.
![image](https://user-images.githubusercontent.com/16850617/62264615-3cfcda80-b453-11e9-9a64-4b3424b117b3.png)
One last question is the WaaSMedicSvc still cannot start even if it is enabled in Wu10Man. 😂

**Comment by WereDev** [comment]
Glad everything is working again.

The WaaSMedicSvc is pretty well locked down by Windows.  It's a hard thing to get running correctly and I'm not sure that you as a user can even run it from the Services window. On the plus side, it's also not a vital part of Windows Update.  All it does is check the Windows Update service and re-enable it if it's been turned off and affect some minor repairs.  It shouldn't stop Windows Update from running.

Out of curiosity, what happens when you try to start it?

**Comment by zsnjuts** [comment]
As before, the error message still is "the system cannot find the file specified" when I try to start WaaSMedicSvc. 😂

**Comment by WereDev** [comment]
blargh...Do you have the file `WaaSMedicSvc.dll` in `C:\Windows\System32`?

**Comment by zsnjuts** [comment]
Yes, I have `WaaSMedicSvc.dll` in `C:\Windows\System32`.

**Comment by WereDev** [comment]
Sorry for not getting back to you.  I had a long weekend away.  Were you able to resolve teh WaaSMedicSvc issue?

**Comment by zsnjuts** [comment]
I didn't pay attention to it the other day. However, `WaaSMedicSvc` is running now. 😂 Thanks!

**Comment by WereDev** [comment]
Glad to year it!
