### ISSUE TITLE
Windows 10 2004 19041.207 no longer respect gpo settings

### ISSUE THREAD

**Issue by sungerbob** [WereDev/Wu10Man#19]
With starting windows 10 2004 version, windows no longer respect gpo settings.

**Comment by WereDev** [comment]
Thanks for the heads up!  Do you happen to have a source for this so that I can dig into it more to see what updates I should possible make?

As an aside, I'm not sure the GPO settings were even working correctly anyway for Home users anyway.  I made a note of such in one of the more recent versions.  Depending on what the 2004 update brings, I will probably just remove that feature all together in the next one.

**Comment by sungerbob** [comment]
I was using this technique for blocking automatic updates. I tested with 3 times (formatting again, again) and 3 times I got automatic updates (including driver).
I made iso with uup-dump; https://uupdump.ml/known.php?q=19041

![55](https://user-images.githubusercontent.com/31207969/79698827-55f72700-8240-11ea-9a57-f770adad941e.PNG)

**Comment by WereDev** [comment]
Thank you for your update.  Seems like the easiest route at this point would be to remove the functionality.  I have an update on my dev branch to start doing that as I work on some other tweaks.

**Comment by englishextra** [comment]
Usually the forst two tabs would ve enough for non-enterprise win 10 users.

That is turning off Windows Services and second table blocking microsoft update servers. I didnt use GPO and it was enough.

**Comment by WereDev** [comment]
I mostly just use the first one.  Shutting the services down completely and turning it back on when I need it seems easiest.  I've been playing with the Pause function as well which I kind of link, but then when the 30 days is up, I'm still surprised by an update, so while it's more likely that the update won't break stuff, I still don't have the control I'd like about it being the right time to update.

**Comment by WereDev** [comment]
Deprecated GPO support and merged in to v4.0.0.
