### ISSUE TITLE
Crashing upon start when there are no permissions to read a registry key.

### ISSUE THREAD

**Issue by Cereal-Killa** [WereDev/Wu10Man#21]
Crashed upon start, seems related to registry permissions, had used another tool before that took the permissions from the windows update service, after I undid that the app was able to start.

[2020-06-15.log](https://github.com/WereDev/Wu10Man/files/4781177/2020-06-15.log)

**Comment by WereDev** [comment]
Hhmm.  Interesting.  Do you know what other tool that was? I'd love to see if I can replicate it here.

**Comment by Cereal-Killa** [comment]
> Hhmm. Interesting. Do you know what other tool that was? I'd love to see if I can replicate it here.

This one: https://www.sordum.org/9470/windows-update-blocker-v1-5/

**Comment by WereDev** [comment]
Looks like this does something similar to what I do in regards to locking down access to things.  Once upon a time you used to be able to just disable the Windows Update service and call it a day, but that doesn't really work anymore.  Microsoft has added scheduled tasks and a Windows Medic service that looks for that situation, as well as a few others, and tries to undo it to restore normal Windows functionality.  To try to shut that down, I also change access rights to areas of the registry as well as the files themselves so that those services can't just restore them and re-enable everything.

The other app apparently adjusts things in a different way that isn't entirely compatible with Wu10Man.  I would recommend not using two different apps that try to accomplish the same thing as they could interfere with each other as you've noticed.  That being said, I'll update mine to fail a little more gracefully.

**Comment by WereDev** [comment]
Added more graceful errors during startup.  Even if one section fails, the rest of the app should still be usable.  Let me know if this helps.

Thanks.
