### ISSUE TITLE
I installed this on a remote machine, Blocked All in the Host file. Connection to remote PC was lost

### ISSUE THREAD

**Issue by tfbkny** [WereDev/Wu10Man#22]
Was working on a Windows 10 Pro using dwservice.net remote connection service. After I set the "Block All" in the 2nd tab (and having allowed the app through Windows Defender), I lost the remote connection as soon as the Host file got saved. 

Since I need to have remote connection using dwservice.net, for me this very helpful utility will be a no go. That's very unfortunate because I needed to stop updates on that PC to be able to use an older printer which after the May 2020 update it had become unable to print because the spooler would not send out the data to the printer (that works via TCP/IP port). After restoring a backup of May 16 2020 for that PC, I regained the ability to print. Microsoft messed up big time with their updates which makes this utility a very valuable help for those who like me would like to install updates only when they've been tried and tested 110%. Thanks!

**Comment by WereDev** [comment]
Hey there.

Does the disconnect happen only when disabling the hosts, or also with the services?  I'm not sure why it would disable the remove connection via the hosts as it shouldn't be disabling any hosts related to dwservice.net.  You can see the full lists of hosts and can also inspect the hosts file to make sure nothing awry is in there.

I can hypothesize about a potential cause though.  Windows 10 sometimes identifies changes to the hosts file as malware and will require some level of security authorization in order to okay that.  It's possible that Windows disable some network connectivity waiting for this authorization in an attempt to protect the user.  I can try do some experimentation on my side to see if that is happening.  It's also possible that dwservie.net wants a connection to one of the URLs that is being blocked.  If you feel so inclined, perhaps you could experiment to see if you lose connection due to a specific host that's being blocked or if it's any host.  If it's a specific host, that would probably mean that dwservice.net also uses that connection.  If it's any host, then it would lead to a confirmation that Windows locks down network access as part of the authorization process.

Finally, the only real magic with Wu10Man is in the first tab shutting down the services.  You don't need to also disable the hosts, that's just sort of an extra precaution.  But if you can disable all the services, that will stop Windows Updates in it's tracks.

I'll see about experimenting with network connectivity when altering the hosts file.  Please let me know if there is anything else I can do or help you with.

Thanks.

**Comment by tfbkny** [comment]
Hi there WereDev/Wu10Man,

Thank you for the much appreciated followup. 

I gave up on it and went the manual route of disabling the services although eventually it'll have to be restored at one point in time, obviously that'd be after MS will have got its "ship" together and issued a proper working fix that won't wreck havoc on the system and disable printers that have been working fine for years.

i won't have time to experiment with the configuration as that's a production PC that's being used by not too savvy people at the other end and I only lucked out when that problem happened since I had a semi-savvy person at hand who helped me restore the configuration so I could then remove the utility and proceed to do the changes manually. 

I would have much preferred the automated option since it would have been a cinch to restore when times comes even for non savvy people, alas for some reason wasn't possible. I understand the hosts should've not caused loss of connection and I was able to add the app to windows 10 firewall. When the firewall "accepted the setting" that's when I lost connection (a few seconds later). There was no confirmation window locking things down (I asked the person looking at the remote screen while on the phone). Hence why I was puzzled by the whole thing and had to drop it not being able to have physical access to the remote machine.

Since MS is being an royal B, I hope this utility will become more user friendly than it is now by allowing also to block only system updates but not the windows defender protection (hence keeping those updates coming).

Thanks again for the free utility which helps filling up the lack of feature by MS which wants to impose its will on the end user by not allowing an indefinite suspension of updates to be managed as users see fit.

All the best and stay safe :)
sf

**Comment by englishextra** [comment]
Sorry to interfere, gent, but dwservice.net as an intermediate tool for controlling remote machine is the key here.

Can you be sure that you know well what's going on in their back-end? 

I use 3 machines behind the router and control two of them from the one next to me. I use tightvnc to visually operate the two others and I block MS hosts (2nd tab) and services (1st tab) when I know for what reasons, and I never encountered connection loss.

Also in terms of security why would you use some third-party service and not known protocols for yourself

I would suggest reading here https://github.com/dwservice/agent/issues/14 and there https://www.reddit.com/r/msp/comments/8etc4u/has_anyone_looked_at_dwservice_as_an_alternative/

Thanks

**Comment by WereDev** [comment]
@tfbkny I'm not sure why the firewall would have been triggered by Wu10Man.  Nothing in it is attempting to access the internet unless you click on some of the links in Help which just go to my site, github, etc.  It's possible that Windows Defender did something (I have been seeing increasing reports that it gets irate with programs edit hosts) but that's all that I can think of.

As far as manually disabling services, I don't think that will work for you in the long run.  Windows 10 has scheduled tasks that happen on a timer as well as after reboots that will re-enable the Windows Update services.  Wu10Man goes the extra step of changing the security access so that those tasks don't have permission to reenable them.  Unless you're running an older build of Windows, you might find that Windows Updates will randomly get turned back on anyway.

@englishextra I'm glad to see that you're having no issues with Wu10Man and dwservice.net.  You commented that you have Windows Defender disabled.  Having Windows Defender disabled would seem to backup my theory that Windows Defender is possibly the culprit here because of the change to the hosts file.  Not sure why that would trigger a Windows Firewall request, but that could be some interplay between Windows Defender, Wu10Man, and dwservice.net because of the changes to the hosts file.  Have you noticed any odd behavior aside from dwservice.net when disabling domains through the second tab?

**Comment by WereDev** [comment]
So I did more digging on this, but I don't really have the ability to setup an environment to try to fully test this.  I'm not sure why updating hosts would change any part of how dwservice works.  I'd be curious to run some tests between updating services and hosts or the combo etc.  Sounds like you've sort of moved on, which I can't blame you for.  I'm going to close this for now.  If you come across anything new, please let me know and I will do what I can to try to help you.

Sorry I couldn't help find an answer for this.

**Comment by tfbkny** [comment]
Couldn't afford to spend time on debugging this and moved on. I just don't use the hosts part and had no issues. So far it's still unknown if it actually works as there's no way of telling if updates are being skipped. Thanks :)
