### ISSUE TITLE
Kill pending updates

### ISSUE THREAD

**Issue by nu8** [WereDev/Wu10Man#25]
I found this tool after I was prompted for some Windows updates. Using Wu10Man,
I already disabled the Windows Update service, but I still have this message in
my system tray:

> Your device needs to restart to install updates. Select a time to restart.

Is this tool able to kill these pending updates?

**Comment by WereDev** [comment]
Hey nu8,

If you're seeing the message "Your device needs to restart to install updates" that means the update is already on your system.  During Windows updates, several files are written to the hard drive over the top of existing files, and several more are staged waiting for resources to free up.  It needs to reboot in order to apply the staged files as they are actively used and to make sure they are loaded correctly into memory.  So, if you're seeing this message, that means the update is already downloaded and mostly applied.  Once it's on the system and asking for a reboot, attempting to interrupt that process can result in an unusable system.

Unfortunately, Wu10Man can't undo this.  Wu10Man is designed to stop the Windows Update download from even starting.  I think your best bet at this point would be to let the update finish, and then see if you can walk it back using [System Restore](https://www.windowscentral.com/how-use-system-restore-windows-10). After that, you use Wu10Man to prevent future updates and download.

**Comment by nu8** [comment]
Interestingly, some time after running Wu10Man the message did go away. However
after restarting the update was in fact done. Hopefully now that I have disabled
no further updates will be done.

In this case update forcefully install Microsoft Edge, which I didnt have, didnt
want, and now cannot uninstall, as the uninstall option is greyed out. Fuck
Microsoft.

Thanks for you help.

**Comment by WereDev** [comment]
Sorry I couldn't help more.

Sadly I have had no success getting rid of Edge either.  Apparently Microsoft didn't learn from their first anti-trust lawsuit and have baked Edge in to the OS itself.  That makes it nearly impossible to get rid of.  I've seen some articles about disabling it by renaming it's folder, but it appears to just come back with the next update.  As a techy, I'm pretty angry with how Microsoft seems to treat everyone like idiots with forced updates and permanent software.  People have been yelling against it for years now, so I doubt it'll change any time soon.

Thanks for using Wu10Man. :)
