### ISSUE TITLE
Error rendering Declutter tab

### ISSUE THREAD

**Issue by pdrive** [WereDev/Wu10Man#31]
using portable version 4.2.0

the first time i tried it gave me a thousand popups of death with the same error. the next times just 1 popup at the time. had to close the app

according to the log "Could not find file 'C:\Windows\system32\declutter.json'." i imagine this is related to the portable app not finding the right resources?
anyway, here's the log
![1](https://user-images.githubusercontent.com/57240186/93400108-52171180-f87f-11ea-839a-9a675da5bba3.JPG)
![2](https://user-images.githubusercontent.com/57240186/93400109-52afa800-f87f-11ea-914a-da36c984210e.JPG)
[2020-09-17.log](https://github.com/WereDev/Wu10Man/files/5235300/2020-09-17.log)

**Comment by englishextra** [comment]
@pdrive As you can read in README - `This is still sort of in BETA, so definitely use with added caution.`

@WereDev I believe there's something with README content - there is some sort of text duplication.

Also I believe that since from the start the goal of the tool was to block win updates, adding the new `fighting bloatware` feature might not be a good idea I have examined a lot of solutions here on GitHub and the problem lies not in creating a good-working tool or, say, simple or universal approach. The problem is that every single user or office admin is likely to have their specific goals. I mean it's a highway to hell trying to create anti-bloatware functionality, and thus the quality of the product can be questioned by users.

Anyways I came here because I like the UNIX approach - one good tool for one task.

**Comment by englishextra** [comment]
@WereDev I believe there's something with README content - there is some sort of text duplication starting from here https://github.com/WereDev/Wu10Man/commit/aba73fd0ff7406ff177f4effe3d337a129ae6231#diff-04c6e90faac2675aa89e2176d2eec7d8

Also I believe that since from the start the goal of the tool was to block win updates (that's why I am here), adding the new `fighting bloatware` feature, the BETA - Declutter tab, might not be a good idea.

I have examined a lot of solutions here on GitHub and the problem lies not in creating a good-working tool or, say, simple or universal approach. The problem is that every single user or office admin is likely to have their specific goals. I mean it's a highway to hell trying to create anti-bloatware functionality, and thus the quality of the product with the primary goal to block updates can be questioned by users.

Anyways I came here because I like the UNIX approach - one good tool for one task.

And one more thing. Disappearance of hosts tab is not a good news to me, This might mean that I don't have control over what tool is doing to achieve the task.

I did all the work that the tool is doing by hand.

- setting permissions to SoftwareDistribution
- disabling windows update
- setting permissions onorchestrator folder
- zeroing ms domains in hosts file

but I was tired to do all that back and forth because sometimes I needed to install something from Windows Store or using TrustedInstaller.

So with Wu10Man I can change everything quickly.

The last but not least. I suggest making it clear who is the tool intended for -  a regular user or someone advanced. I believe it's for the latter.

**Comment by WereDev** [comment]
@pdrive Thanks for letting me know about this issue.  You shouldn't have gotten a dispatcher error, just an error about rendering the tab due to the missing file.  This probably was introduced when I moved the binding code in the last version.  I'll look into that to see if I can make the error handling better.

As far as the path, I find it curious that it's looking for the file in `c:\windows\system32`.  It should be looking for the file in the folder in which Wu10Man is executing.  Did you extract the files into `c:\windows\systme32`?  If so, that is strongly advised against and should be executing somewhere else.  If not, can you describe more about how you're running it?


@englishextra Thanks for your input.  I did some last minute rearranging of the readme with the last version and was apparently a bit sloppy about cleanup.  Thanks for the heads up.

Regarding the audience for the application, it was initially just me.  I created this because I couldn't find a simple tool to disable the stupid Windows Update stuff.  People seem to find it useful so I've maintained it.  As far if it's intended for home users or more advanced users, probably a bit more advanced as its better if people understand what's going on, but I do try to keep the interface simple so that really anyone can use it.

The Declutter stuff was added as it was a more recent annoyance when I was setting up some new systems.  It's beta because like you, I noticed that this is a problem whose solution is usually fraught with trouble so this is sort of me tinkering.  For example, it works well to clean up much of the bloatware that's installed, but I haven't figured out how to handle the bloatware that's just icons on the start menu and installs after you click on it.  Hence it's just in beta and since this project really is just be tinkering as I have time, it'll probably be a long time since this gets fully fleshed out, if ever.

**Comment by pdrive** [comment]
no, never used system32. the path is: **C:\Apps\Windows Update Manager\Wu10Man_Portable_4.2.0\Wu10Man.exe**
C:\Apps\ is a folder i use for portable apps without the permissions of /program files/. 
i just went to the C drive and created a folder, extracted the portable zip file, ran Wu10Man.exe

![apps](https://user-images.githubusercontent.com/57240186/93405651-d7092780-f88d-11ea-9edf-357d70eb663b.JPG)

just want to say i appreciate the declutter stuff. it's always nice to have. hopefully ill be able to use it soon :)

**Comment by WereDev** [comment]
So I haven't been able to reproduce this error yet.  If I delete the `declutter.json` file, then the error gives me the correct folder.  I do get the thousand other popups though.  I created patch release 4.2.1 to deal with this issue.  Try that and let me know if that works for you.  Also, this is probably a stupid question, but you are unzipping all the files?  There should be 18 of them.  Also, when you run it, are you double clicking on the icon in the folder, or are you trying to execute it from a command prompt?

**Comment by pdrive** [comment]
yes, i unzipped the zip file. extract all.
this is the content of the folder
![yep18](https://user-images.githubusercontent.com/57240186/93691318-ea153500-fae3-11ea-94a5-8d90522e6f90.JPG)


just tested 4.2.1. everything seems to be working now. declutter tab loads after a second and i was able to select and remove some apps
not getting any errors. 👍 
[2020-09-20.log](https://github.com/WereDev/Wu10Man/files/5250896/2020-09-20.log)

**Comment by WereDev** [comment]
Weird. Well, I'm glad it's working now!  Let me know if you run across any other issues.
