### ISSUE TITLE
Disabled all 3 services, but now System Event Log contains many errors from Medic service

### ISSUE THREAD

**Issue by MBilderbeekALSI** [WereDev/Wu10Man#37]
Thanks for making this tool. I'm trying it out and was able to disable all 3 services to block Windows Updates. (Goal is to be able to manually trigger Windows updates, most importantly Defender updates.)

The Medic service looks disabled, or at least broken:
![image](https://user-images.githubusercontent.com/80956076/111769639-befc7a00-88a9-11eb-9db7-a003c866d634.png)

I do see it's effective (no more updates are downloaded), but there are also many errors in the System Event Log:
![image](https://user-images.githubusercontent.com/80956076/111769864-fd923480-88a9-11eb-9cae-1afe5e827226.png)

This is polluting the log. 

My question is: was this the intended behavior, or am I missing something and doing something wrong?

**Comment by WereDev** [comment]
Hey @MBilderbeekALSI 

I would say these errors are somewhat expected.  The errors are a result of Windows trying to start the Medic Service and can't because it was disabled by Wu10Man.  I am curious as to what is trying to start the service that frequently though.  My best guess is there is a Windows Task trying to start or recover what it sees as an issue with the Windows Update system.  Another user had brought up some Tasks that it might be nice to disable with this app, but now I can't find that issue.

Anyway, my guess as to what is going on is that a Windows Task is trying to start or recover Windows Update and can't because Wu10Man shut it all down.

As I get time, I can do some digging to see what Task(s) might be trying to do this and maybe add that as something additional that Wu10Man can update.

**Comment by englishextra** [comment]
@MBilderbeekALSI 

> This is polluting the log.

Of course it will.

@WereDev 

I wouldn't bother so much about it. If a person is professionally involved in programming or IT administering, they wouldn't have asked a question like this.

**Comment by MBilderbeekALSI** [comment]
@WereDev Thanks. If it's possible to prevent the other mechanism from checking this and polluting the log, the solution would be a bit cleaner, or at least easier to still read the logs. 
I do realize this tool is a bit of a hack.

I am trying to make a proper Windows 10 IoT image for embedded usage, and the Defender update checks are disturbing the system.  I have followed Microsoft's documentation to manage these settings. E.g. you can set up a group policy to Never let Defender check for definition updates... but this simply has no effect: Windows Update will do it anyway.
Why would MS document it, if it's not having any effect?

I suppose you ran into this as well and then decided to create your tool to work around this.

**Comment by dennyamarojr** [comment]
For this problem of the System event Log containing the the errors from the medic service is because update orchestrator may call the service and fail to start the scheduled scan or the scheduled start. (need to see if disabling the update orchestrator tasks will fix the issue).

**Comment by WereDev** [comment]
I spent some time looking into dealing with Tasks this weekend and it seems that those are more difficult to circumvent the security than the Services were.  The biggest problem so far as that I can't seem to claim ownership or manipulate the access rights to the Task as easily as I did with Services.  I have a few ideas that I'm playing with which are all a little wonky:

1. The first is doing something like PsExec which is to spawn a background Service that runs as Local System to get the appropriate access and then pipe commands through the service.  I'm not a huge fan of spawning and then removing a background Service that has uber access to the system as it would be too easy to exploit by other software to compromise the machine.  There's several blogs about this in relation to PsExec so I'd rather not recreate that issue with Wu10Man.  But, if I can think of a good way to secure it, then this would open up other avenues for redoing other functionality in Wu10Man to use similar workaround to Windows locking things down.
2. The second one is that I can create a Scheduled Task that runs as System to disable other Tasks.  I have experimented with this and it works well, though it is basically using C# to create a Task that runs a Powershell script.  This feels a little hacky to me which I don't like, but it does have the benefit of not creating the same potential avenue for compromising the system that the option 1 does, and would be easier to build & maintain overall.
3. The last one, which I really don't like, would be to move the Task out of the Tasks folder.  This would stop it from being able to have any information about running the Task, so it couldn't execute.  I don't like this path though either as there are 3 different systems the work together to maintain a Task.  One is the file itself, then there is the registry entry, but also some other  mechanism that I haven't entirely yet figured out.  Moving the file leaves these other two things in tact and I don't know what the affect would be.  It might even be that it creates more errors in the Event Log as the Task system is now out of sync with itself.  Having three moving pieces for enabling/disabling a Task also means there's a higher chance that it would get screwed up some how.

If people have some thoughts of suggestions, I would love to hear them.  I'm currently leaning towards option 2 but am still doing some digging to see if I can figure out how and where the security information for Tasks is stored (I know that some is the file and some is the registry, but there is a third one somewhere) that might provide a better avenue for taking ownership of the Task so that I can change it's properties similar to what I do with Services.

**Comment by krrr** [comment]
You can rename UsoClient.exe (used by those protected scheduled tasks) after disabling services, so that windows can't enable update services again. No error message will be logged

**Comment by WereDev** [comment]
[Wu10Man 4.3.0](https://github.com/WereDev/Wu10Man/releases/tag/v4.3.0) is up.  This has the an option to disable Scheduled Tasks.  Hopefully this helps solve the problem with the Event Log being full of shenanigans.  Let me know if this works ok for you.

**Comment by MBilderbeekALSI** [comment]
Nice! Which scheduled tasks does it disable?

**Comment by WereDev** [comment]
There's quite a few that are supposed.  Here's the list along with the Task path if you want to find them in Scheduled Tasks.

 - Schedule Scan: Microsoft\Windows\UpdateOrchestrator\Schedule Scan
 - Schedule Scan Static Task: \Microsoft\Windows\UpdateOrchestrator\Schedule Scan Static Task
 - Schedule Work:  \Microsoft\Windows\UpdateOrchestrator\Schedule Work 
 - Report Policies: \Microsoft\Windows\UpdateOrchestrator\Report policies 
 - Update Model Task: \Microsoft\Windows\UpdateOrchestrator\UpdateModelTask 
 - UX Broker: \Microsoft\Windows\UpdateOrchestrator\USO_UxBroker 
 - Remediation: \Microsoft\Windows\WaaSMedic\PerformRemediation 
 - Scheduled Start : \Microsoft\Windows\WindowsUpdate\Scheduled Start

I think this will catch the issue that you see as well as any other related tasks for Windows Update.  The few that I didn't include are the tasks that handle things like reboots as that should only happen if there is a Windows Update in progress and I don't really want to mess with that part of the process too much.

**Comment by MBilderbeekALSI** [comment]
Do you have any idea what the risk is on side-effects? Some of these do not seem to be directly related to disabling Defender/updates.

**Comment by WereDev** [comment]
All the ones in the "UpdateOchestrator" are directly related to Windows Updates as is the "Schedule Start".

The "PerformRemediation" task is indirectly related to Windows Updates.  That task is what kicks off the Medic Service that looks for and attempts to correct issues with Windows Updates.

I have not done a full evaluation of risks per se, but these were identified by path and various online resources as the items most directly related to Windows Updates.  In relation to the original ask of this ticket, it's the PerformRemediation task that is kicking off the Medic Service that is showing up in the Event Log.
