### ISSUE TITLE
Cannot stop the update on my laptop

### ISSUE THREAD

**Issue by jekyllgrim** [WereDev/Wu10Man#40]
I have Windows 10 Home build 18362 on my Xiaomi laptop, and unfortunately WUB doesn't seem to affect it at all. I have all 3 services diabled, yet the system notified me it has a restart scheduled in 10 minutes (and in fact yesterday it restarted on me withou any warning and started installing an update; I had to force-shutdown it to make it roll back to the last restore piont).

`C:\Windows\SoftwareDistribution\Download` is actually empty, but the update is clearly unavoidable in my case...

**Comment by WereDev** [comment]
By WUB, do you mean Windows Update Blocker?  I'm not entirely familiar with that software.  This is the GitHub for Wu10Man which is a different piece of software.

A brief Googling though and I think I know why WUB may not be effective here.  Most of the blockers will simply disable the services related to Windows Update.  Windows Update Service (wuauserv) and Windows Medic Service (WaaSMedicSvc) are the two main ones.  One of the other tangentially related ones are the Windows Module Installed (TrustedInstaller).  WUB disables those and a few others.

Here's the rub though, Windows has several Scheduled Tasks that will occasionally go through and turn them back on.  These existed even a couple years ago when your build came out.  I haven't heard of the other Windows Update apps like WUB doing anything to stop this so it is likely that while it was disabled in WUB, Windows reenabled them.

It was actually that problem the led me to making Wu10Man to begin with.  Wu10Man goes the extra step of moving the files as well, so that even if it wanted to restart the service, the file is missing.  It used to change the credentials that the service ran under as well so that it couldn't start due to security reasons, but that became a bit too risky for my tastes as if something happened to Wu10Man, it was difficult to undo that step manually, where renaming a file is pretty easy.

The latest version of Wu10Man also adds functionality to allow for disabling some of the Schedule Tasks associated with running and repairing Windows Update configurations.  I don't use that personally, but it was something requested by another user.  Just disabling the services via Wu10Man has been sufficient for me.

One other thing of note is that the service that controls the reboot process for Windows Update is separate from the Windows Update Service itself and not something that Wu10Man currently handles.  That's because if there is a pending update on your machine, it can potentially break a lot to try to undo it and I don't particularly want to go down that path.

I hope that helps you out a bit.  Let me know if you have any other questions.

**Comment by jekyllgrim** [comment]
Hey, thanks for the reply. Sorry, I was referring to Wu10Man; I just used "WUB" out of habit since that was what I'd tried before but it didn't work and it doesn't get any updates. Your point about the restart service being separate seems to apply to my case, though, since I eventually restarted my laptop, and despite saying "Update & restart" in the Start menu, it didn't actually update. But I wonder what I can do about this now, because it seems to still think  there's a pending update, even though it can't actually download it. Maybe it'll resolve itself at some point.

**Comment by WereDev** [comment]
If it already has "Update & Restart" in the Start menu then there is already a pending update that needs to get applied.  I'm not sure if Wu10Man can stop that or what would happen if the Windows Update service is stopped, though I imagine that it wouldn't actually be able to update Windows so that little orange dot would remain in the Start menu.

There's no way that I'm aware of to reverse an Update once it's in progress.  As I mentioned earlier, some stuff is updated live while others require a reboot, hence the "Update & Restart".  I would reeanble the various services, let the update finish and then immediately disable the services again in Wu10Man once that update has completed.
