### ISSUE TITLE
Scheduled task (beta) cant disable

### ISSUE THREAD

**Issue by zekecarter** [WereDev/Wu10Man#43]
![1](https://user-images.githubusercontent.com/83554130/125369185-69a91480-e341-11eb-943e-0189137c1b54.png)
can generate another update ?

**Comment by WereDev** [comment]
I do not understand the question.

If you disable the Windows Services, from it's tab, you don't really need to disable Scheduled Tasks.  This tab was added as some user's noted that the Event Log was filled with errors.  Those errors were caused by various scheduled tasks (the ones in your screen shot) were trying to start an Update but were failing since Services were disabled.  Even among the Scheduled Tasks, the only ones I think you really need to disable from Windows Services perspective are "Windows Medic - Remediation" and "Windows Update - Scheduled Start".  I'm not sure what leaving them all enabled except for "Update Orchestrator - Schedule Work" will really do, but I think the "Update Orchestrator" series are only used once an actual Windows Update has started; so leaving that disabled I think will still allow a Windows Update to start, but may leave it in an incomplete state. This is still in Beta as I haven't tested various combinations or their effects nor has there been enough time for users to report any issues they've noted, so please use it with caution.

**Comment by zekecarter** [comment]
Thank you very much for answering.

Your analysis is correct, I tried to disable the tasks to prevent any background process from trying to run the windows updates, but, when trying to disable them, they remained active, I thought it required updates to disable those tasks. 😅
