### ISSUE TITLE
WU10MAN version 4.3.0 does not pause updates on win10 build 19043.1266

### ISSUE THREAD

**Issue by zekecarter** [WereDev/Wu10Man#45]
hello how about after the last update that microsoft released we can not pause for almost indefinitely, updates windows 10 or windows 11 versions 19043.1266

**Comment by WereDev** [comment]
As a note, pausing isn't really a Wu10Man feature.  Its part of the Windows Update system.  I added a UI because Windows only lets you go out a certain amount of time.

Also, the Pause feature of Windows Update does not necessarily stop updates.  Microsoft can and apparently has forced updates through anyway if they've deemed it an important enough security update.

I'll update the text to make this more clear in the next release.
