### ISSUE TITLE
What will this do if I've already 'broken' the updates?

### ISSUE THREAD

**Issue by Darkmaster006** [WereDev/Wu10Man#46]
So, in my need to disable updates (and Win Defender) because they literally make Windows unusable in my laptop, I followed these steps: https://www.wintips.org/how-to-turn-off-windows-10-updates-permanently/ so that WinUpdate does not work (hopefully permanently with the latest changes, but it does seem to recover itself after a few power offs and ons (for example, the regedit stuff gets turned back to its default values, and the medic seems to fix itself). Right now, though, this is what I see:
![imagen](https://user-images.githubusercontent.com/21136515/146497015-a0a227d2-7461-4c0f-a4b8-384e125dfbb8.png)
Is it "safe" to use this program, or will it do something undesirable? Thank you.

**Comment by WereDev** [comment]
Alot of the tips online about how to disable Windows Update don't really work.  Or more specifically, to do for a little while but not for very long.  There are several layers that Microsoft has added to Windows to undo many of these things and try to reenable Windows Update anyway.  The main things that do this are the Windows Update Medic Service and Trusted Installer as well as a small host of Windows Scheduled Tasks that look to fix issues.  Those instructions do cover most of those things so I'm not sure which part might have turned it all back on.

My software does a fair amount to disable the services including disabling the services, setting security so that local services shouldn't be able to undo that, and moving files just in case.  There's another tab to take care of Scheduled Tasks as well.

If you've run through these instructions I'm not entirely sure how Wu10Man will react to various settings, but nothing jumped out at me as an issue.  Using this software also makes it much easier to undo the settings for when you do want to run updates, which you should do occasionally.

That being said, changing the settings of services, scheduled tasks, and the registry should always be done with caution.  When in doubt, make sure to create a [System Restore Point](https://support.microsoft.com/en-us/windows/create-a-system-restore-point-77e02e2a-3298-c869-9974-ef5658ea3be9) so that if something does go wrong, it becomes easier to restore to a previous state.

**Comment by Darkmaster006** [comment]
> Alot of the tips online about how to disable Windows Update don't really work. Or more specifically, to do for a little while but not for very long. There are several layers that Microsoft has added to Windows to undo many of these things and try to reenable Windows Update anyway. The main things that do this are the Windows Update Medic Service and Trusted Installer as well as a small host of Windows Scheduled Tasks that look to fix issues. Those instructions do cover most of those things so I'm not sure which part might have turned it all back on.
> 
> My software does a fair amount to disable the services including disabling the services, setting security so that local services shouldn't be able to undo that, and moving files just in case. There's another tab to take care of Scheduled Tasks as well.
> 
> If you've run through these instructions I'm not entirely sure how Wu10Man will react to various settings, but nothing jumped out at me as an issue. Using this software also makes it much easier to undo the settings for when you do want to run updates, which you should do occasionally.
> 
> That being said, changing the settings of services, scheduled tasks, and the registry should always be done with caution. When in doubt, make sure to create a [System Restore Point](https://support.microsoft.com/en-us/windows/create-a-system-restore-point-77e02e2a-3298-c869-9974-ef5658ea3be9) so that if something does go wrong, it becomes easier to restore to a previous state.

Thank you very much. Yes, those tips there are pretty comprehensive, but it seems something's missing (namely, I can't modify wuauengl.dll for some reason, plus my Windows is Home version (still haven't found a way to update it to pro, so my gpedit has been added by me and I believe doesn't have all the options available). Either way, I'd normally make a restore point, but honestly, I have a partition just for Windows and if it dies, I'll just reinstall, easier and I don't really care. I'm all in haha. Anyways, the updates have come back (seems like the edits last 3 to 5 restarts), I'd paused them before, although it seems like the pause time, if I keep on making the edits, will go on indefinitely (but I'm not sure):
![imagen](https://user-images.githubusercontent.com/21136515/146693645-3eb83129-3f35-4da0-92ea-eb55a73445cc.png)

Anyways, seeing this came back, I'll run your program and let you know how it goes. Thank you very much again.
