### ISSUE TITLE
Wu10Man blocked updates and now won't open

### ISSUE THREAD

**Issue by Anything-Simple** [WereDev/Wu10Man#50]
Hey everyone, 
Wanted to say thanks for a great program, we use it a lot and works really well. 
One issue to report though, Wu10 was installed on a Mac mini (2014) system using macOS High Sierra 10.13.6 dual booted with Windows 10 (ver. 10.0.18362). We have used this set up on a number of systems with this same config and it's always worked fine. Wu10 has blocked Windows updates successfully but now refuses to open, in order to do planned updates I tried uninstalling, no change, reinstalled it and it still won't open.
Perhaps re-enabling the specific services in Windows or unblocking the host files in the registry manually? Do you have specific lists of either of these for reference?
Any recommendations would be amazing!

**Comment by WereDev** [comment]
I don't have ready instructions for that, but I can maybe put something together.  Part of the issue is there are some workarounds used to get around some security issues that Windows has that are difficult and sometimes not possible to do manually.

That being said, would you be able to send me the logs from when you try to open it?  The logs can be found in the Logs folder either from the install directory, or if you use the portable (not-installed version) then in the Logs folder of the directory holding the executable.

**Comment by WereDev** [comment]
Are you still having issues with this?

**Comment by Anything-Simple** [comment]
Hello, sorry for the delay in getting back to you, I haven't logged in here for a while. We were able to rectify the issue with updating Windows then re-downloading the latest version of Wu10 from here. Thanks for your response though, we are continuing to use the app without any issues, so please mark this closed :)
