### ISSUE TITLE
is this still mainteined?

### ISSUE THREAD

**Issue by Minibus93** [WereDev/Wu10Man#51]
Basically title

**Comment by WereDev** [comment]
Kind of.  I've mostly moved over to Linux as my main driver but I am keeping tabs on this.  That being said, I don't currently have plans to support this on whatever shenanigans Windows 11 brings to the table.

**Comment by WereDev** [comment]
Finally got around to another release.  Anything in particular you're looking for?

**Comment by killtux** [comment]
is it possible to just prevnt windows 10 from automatic rebooting after downloading/installing update so i could choose when to reboot the system myself?

i connect to a win10 system via RDP and if there is no active connection, windows just reboots at night and kills my chia farming client.

**Comment by RomainLpt31** [comment]
Hello, does it work on Windows 11 ? Does Microsoft add more services or changed them on their new Windows Update ?
Thanks in advance

**Comment by WereDev** [comment]
> is it possible to just prevnt windows 10 from automatic rebooting after downloading/installing update so i could choose when to reboot the system myself?

Not really.  Once the Windows Update process has run, it kind of takes over from there.  You could maybe stop it by reenabling Wu10Man before it reboots, but I wouldn't recommend it.  Windows Update updates some files on the fly and leaves other for when you reboot as they're often in use.  The result is that continuing to use the system or do other things while that reboot is pending could cause issues.

> i connect to a win10 system via RDP and if there is no active connection, windows just reboots at night and kills my chia farming client.

My suggestion would be to only disable Wu10Man and then run updates when you know you have some time to babysit.  That's kind of the sad part to Wu10Man is you don't get all the fun of automated updates.  Another option would be to set Windows to automatically log in on reboot and have the chia farming client run on start.  Not sure if or how that setup might work for you since you're using RDP.

**Comment by Voyager69** [comment]
Estuve probando la aplicación y mas allá de que desactive las actualizaciones de windows services y de Scheduled task, las peticiones hacia "ctldl.windowsupdate.com" siguen realizándose.

**Comment by WereDev** [comment]
I assume you're on Windows 11.  I've seen some things still sneaking through on 11.  Though if you're using the Pause function and not fully disabling services, calls will still be made via Pause as it's looking for urgent security updates that can sometimes still get installed even if the Pause date is set out.
